# https://gitversion.net/docs/reference/configuration#branch-configuration
mode: ContinuousDeployment
branches:
  release:
    regex: ^release?[/-]
    tag: ""
  feature:
    regex: ^feature?[/-]
    tag: rc
  pull-request:
    tag: pr
  main:
    tag: rc
ignore:
  sha: []
