# https://gitversion.net/docs/reference/configuration#branch-configuration
mode: ContinuousDeployment
branches:
  feature:
    regex: ^feature?[/-]
    tag: rc
  pull-request:
    tag: pr
  main:
    tag: rc
ignore:
  sha: []
