# https://gitversion.net/docs/reference/configuration#branch-configuration
next-version: 0.5
mode: ContinuousDeployment
branches:
  release:
    tag: ""
  feature:
    tag: "dev"
  main:
    tag: "preview"
ignore:
  sha: []
