steps:
- bash: |
    echo "##vso[build.updatebuildnumber]$(major).$(minor)-PullRequest.$(prpatch)"
  condition: eq(variables['Build.Reason'], 'PullRequest')
  name: SetPRBuildName
- bash: |
    echo "##vso[build.updatebuildnumber]$(major).$(minor)-$(Build.SourceBranchName).$(brpatch)"
  condition: and(ne(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))
  name: SetBranchBuildName
- task: Docker@2
  displayName: Build docker image
  inputs:
    containerRegistry: 'hackathon2356104672'
    repository: rc/api/graphqlsample
    command: buildAndPush
    Dockerfile: ./GraphQLSample.Api/Dockerfile
    buildContext: .
    tags: |
      latest
      $(Build.BuildNumber)-$(Build.SourceVersion)