name: Pull Request Build

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
      - release/*
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Check out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml

      - name: Restore dependencies
        run: dotnet restore

      - name: Build dotnet
        run: dotnet build --configuration release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} --no-build --verbosity normal

      - name: Package nuget
        run: dotnet pack --configuration release -o:package /p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersion }}
